service: baianat-invoice-qrcode-generator

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1

functions:
  generate:
    handler: handler.generate
    events:
      - httpApi:
          path: /qr
          method: get
plugins:
  - serverless-apigw-binary
custom:
  apigwBinary:
    types:
      - 'image/jpeg' 